### ISSUE TITLE
Agent Overview -- Action repartion

### ISSUE THREAD

**Issue by Tezirg** [mjothy/grid2viz#10]
Hello, I would like to report an issue regarding the actions distrubution histogram.

 - Using the default logs provided in `grid2viz/data/agents`, and default `install pip3 install -r requirements.txt` in a brand new virtualenv

-  Select **Scenario0037**

-  Navigate to **Agent Overview**

- Notice the action taken at step 1 on power line `12_13_19`:
![grid2viz-lineaction](https://user-images.githubusercontent.com/10632501/78145759-9299e480-7431-11ea-9c09-238d97335111.png)

```
This action will:
	 - NOT change anything to the injections
	 - NOT perform any redispatching action
	 - NOT force any line status
	 - switch status of 1 powerlines ([19])
	 - NOT switch anything in the topology
	 - NOT force any particular bus configuration
```

- However, the line distribution histogram doesn't show any action for line `12_13_19`:
![grid2viz-distrib](https://user-images.githubusercontent.com/10632501/78145834-aba29580-7431-11ea-937d-cdff47bef832.png)

**Comment by vinault** [comment]
This is adressed in 7138a50031e8ae0a9a65a4fb78e1301cadec6608 and e766c30ef912724c63246b15c25db391be49c580.
