### ISSUE TITLE
Reward graph ending even though there is game over

### ISSUE THREAD

**Issue by Ashargin** [mjothy/grid2viz#17]
Suppose we have an agent that succeeded to finish the scenario (DoNothing here) and another one that failed (TopologyGreedy here).
When studying the successful agent, there is no problem with the graph:
![grid](https://user-images.githubusercontent.com/25967564/82672685-f4601900-9c40-11ea-9204-93fb0c6cde29.png)
Then, studying the agent that failed, we can see that the graph ends sooner because of the game over, which is normal:
![grid2](https://user-images.githubusercontent.com/25967564/82672782-1c4f7c80-9c41-11ea-837a-7c13aff2adf4.png)
But then, going back to the successful agent, the graph still ends at the time when the other agent encountered a game over, even though it is not plotted here:
![grid3](https://user-images.githubusercontent.com/25967564/82672886-3f7a2c00-9c41-11ea-9887-96a45722f35b.png)

Data used:
"rte_case14_realistic" environment
scenario 000 (the first one)
max_iter : 300
agents: DoNothing and TopologyGreedy

This can be reproduced with:
```
import os
import grid2op
from grid2op.Runner import Runner
from grid2op.Agent import DoNothingAgent, TopologyGreedy
import shutil

path_agents = 'agent_logs'
max_iter = 300
env = grid2op.make('rte_case14_realistic')

for agentClass, agentName in zip([DoNothingAgent, TopologyGreedy],
                                 ["DoNothingAgent", "TopologyGreedy"]):
    path_this_agent = os.path.join(path_agents, agentName)
    shutil.rmtree(os.path.abspath(path_this_agent), ignore_errors=True)
    runner = Runner(**env.get_params_for_runner(),
                    agentClass=agentClass
                    )
    res = runner.run(path_save=path_this_agent, nb_episode=1, 
                     max_iter=max_iter)
    print("The results for the {} agent are:".format(agentName))
    for _, chron_id, cum_reward, nb_time_step, max_ts in res:
        msg_tmp = "\tFor chronics with id {}\n".format(chron_id)
        msg_tmp += "\t\t - cumulative reward: {:.6f}\n".format(cum_reward)
        msg_tmp += "\t\t - number of time steps completed: {:.0f} / {:.0f}".format(nb_time_step, max_ts)
        print(msg_tmp)
```

grid2op version: 0.9.1.post1

System specifications:
System edition: Windows 10 Family
System version: 18362.836
Processor: Intel(R) Core(TM) i7-6700HQ CPU @2.60GHz 2.59GHz
RAM memory: 16,0 Go
Product ID: 00325-95800-00000-AAOEM
System type: 64 bits operating system, x64 processor

**Comment by vinault** [comment]
Hi @Ashargin,

this is a reproducible bug, thanks.
