### ISSUE TITLE
Properly counting topological actions

### ISSUE THREAD

**Issue by marota** [mjothy/grid2viz#21]
In the current implementation, the count of actions for topology was not yet accurate in Agent Overview table and Histogram.

The methods impact_on and effect_on should be used in their latest version to distinguish when the action was actually intended to modify the status of a line or the topology of a substation

**Comment by marota** [comment]
Rappel du besoin: 

Pour chaque timestep (donc chaque objets « action ») nous avons besoin :

-          Du nombre d’actions dites « sur les lignes »

-          Des éléments qui sont ciblés uniquement par les actions dites « sur les lignes » (lignes et substations)

-          De la nature du changement induit sur ces éléments ciblés

 

-          Du nombre d’actions dites « sur les substations »

-          Des éléments qui sont ciblés uniquement par les actions dites « sur les substations » (substations et equipements)

-          De la nature du changement induit sur ces éléments ciblés (déconnection, reconnection, nœud d’origine, nœud d’arrivé)

 

Le plus important étant de pouvoir distinguer au sein d’une action, la partie qui est qualifiée de « sur les lignes » et la partie qui est qualifiée de « sur les substations ».

En particulier, lorsque nous aurons plusieurs « actions » par timestep, comment gérer le cas ou :

Exemple :

Deux actions agissent sur les substations 3 et 6 (transfert tous les load du nœud 1 vers 2), et une action agis sur la ligne (3) qui lie ces deux substations pour la deconnecter. On souhaite avoir les données suivantes :

-          Du nombre d’actions dites « sur les lignes » [1]

-          Des éléments qui sont ciblés uniquement par les actions dites « sur les lignes » (lignes et substations) [line : 3, sub : [3,6]]

-          De la nature du changement induit sur ces éléments ciblés [line 3 déconnectée de sub 3 et sub 6]

 

-          Du nombre d’actions dites « sur les substations » [2]

-          Des éléments qui sont ciblés uniquement par les actions dites « sur les substations » (substations et equipements) [sub : [3,6], equipment :{load :[1,2,3,4]}]

-          De la nature du changement induit sur ces éléments ciblés (déconnection, reconnection, nœud d’origine, nœud d’arrivé) [load deconnectée du nœud 1 : [1,2,3,4] load connecté au nœud 2 : [1,2,3,4]]

**Comment by marota** [comment]
A unitary test should be made for that function

**Comment by BDonnot** [comment]
Un bon point d'entrée est la fonction: 
https://grid2op.readthedocs.io/en/v0.9.3/action.html#grid2op.Action.BaseAction.get_types
On peut aussi regarder
https://grid2op.readthedocs.io/en/v0.9.3/action.html?highlight=get_topological_impact#grid2op.Action.BaseAction.get_topological_impact

Et bien sur
https://grid2op.readthedocs.io/en/v0.9.3/action.html?highlight=as_dict#grid2op.Action.BaseAction.as_dict
entre autres.

Benjamin

**Comment by marota** [comment]
@vinault pour calculer la distance topologique à la topologie de référence, on le fait ainsi:
- si statut d'une ligne différent, on incrémente la distance de 1
- si topologie d'un poste différent, on incrémente la distance de 1 uniquement (on ne compte pas la différence entre chaque élément d'un poste, ce qui semble être le cas actuellement)
