### ISSUE TITLE
Add troubleshooting section in Readme

### ISSUE THREAD

**Issue by camiloromers** [mjothy/grid2viz#38]
Hello,

Some Mac users have been experimenting troubles when launching the app. It would be useful to add in the readme a troubleshooting sector with this case and probably more reported by other users.

Particularly and for other Mac users, the message received when laughing the app s the following:

`socket.gaierror: [Errno 8] nodename nor servname provided, or not known`

In order to overcome the issue, users have to update the file located at `/etc/hosts` with the following formation:

`127.0.0.1       value_get_after_print_$HOST_in_the_terminal`

For instance:
`127.0.0.1 x86_64-apple-darwin.....`

source:
https://stackoverflow.com/questions/39970606/gaierror-errno-8-nodename-nor-servname-provided-or-not-known-with-macos-sie

**Comment by vinault** [comment]
Hi @camiloromers,

can you make a PR with the modified README.md to inclue this info ? 

Thanks !

**Comment by vinault** [comment]
Hi @camiloromers,

I merged your PR. Thank you very much. i'm closing the issue.
