### ISSUE TITLE
Adding a grid plot on scenario overview with basic info

### ISSUE THREAD

**Issue by marota** [mjothy/grid2viz#45]
On scenario overview, having a layout of the grid and knowing where productions and loads are, what type they are, with possibly their max value in the scenario, could be quite informative. 

This could be a different "onglet" with the load curve: you could either see the load curve or the grid plot

**Comment by marota** [comment]
On souhaiterait afficher pour un scenario donné:

- le max de puissance active atteint pour chaque groupe
- avoir une colloration différente pour distinguer les différents type de production (thermique, éolien, ...)
- le max de consommation atteint pour chaque conso

Exemple de code:

from grid2op.PlotGrid import PlotPlotly
#from grid2op.PlotGrid import PlotMatplot
plot_helper = PlotPlotly(env.observation_space, 
                          sub_radius=14, 
                          load_radius=10, 
                          gen_radius=10,
                          width=950,
                          height=600,
                        )
plot_helper._line_bus_radius = 6
plot_helper._line_arrow_width = 10
plot_helper._line_arrow_len = 17


fig = plot_helper.plot_info(gen_values=env.gen_pmax)
fig.show()

![image](https://user-images.githubusercontent.com/5496312/95755988-6c3ce780-0ca5-11eb-91ed-00965e856e99.png)

**Comment by vinault** [comment]
Done in 1623341e.
