### ISSUE TITLE
Maintenance duration graph takes too much space In agent overview

### ISSUE THREAD

**Issue by marota** [mjothy/grid2viz#49]
In agent overview, the Maintenance duration graph takes a lot of space while displaying almost no information

![image](https://user-images.githubusercontent.com/5496312/96004940-45fd8000-0e3c-11eb-87ee-f2d3f1d91b76.png)

**Comment by marota** [comment]
It would be most useful as of now to do the following:

- Add number of maintenance indicator on the right
- Replace the actions Distibutions by a grid plot where we highlight :

1. the localization of actions over the scenario 
2. the localization of overloads and maintenance

**Comment by vinault** [comment]
Done in cb4dfc8a.
