### ISSUE TITLE
Readme issue

### ISSUE THREAD

**Issue by BDonnot** [mjothy/grid2viz#5]
Hello,

Some new modifications has been done to integrate a "command line interface" with grid2viz. But i think the "readme" does not mention this function, which requires, I think, less manual settings than the historic way.

Would it be possible to reflect these changes in the readme ?

Also, the image of the application displayed (especially for the layout of the grid) should be redone with the proper layout of the graph i think. It's hard to see the application has this capability with the image displayed.

Benjamin

**Comment by marota** [comment]
A faire en fait
