### ISSUE TITLE
Bug when selecting a scenario (because of matplotlib plots ?)

### ISSUE THREAD

**Issue by marota** [mjothy/grid2viz#53]
When launching grid2viz (on the demo dataset for example) and selecting a scenario, an error occur on MacOs.

"Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!"

Probably related to the matplotblib plot in the Scenario overview and related to that https://github.com/matplotlib/matplotlib/issues/14304/

"If you are running a webserver and using it to save Matplotlib make sure to set the backend to a non-interactive one (matplotlib.use('agg') or matplotlib.pyplot.switch_backend('Agg')) so that your server does not try to create (and then destroy) GUI windows that will never be seen (or if they are will be more of a nuisance)."

**Comment by vinault** [comment]
@marota : Should we close this issue ?

**Comment by marota** [comment]
Done in 65b4ea46d82ab4ee077d6d9d39bf4dbe18c7f2b8
