### ISSUE TITLE
Agent Overview / Agent Study not enabled

### ISSUE THREAD

**Issue by jhmenke** [mjothy/grid2viz#7]
Having loaded my individual scenario, i can click on it on the scenario selection. Then i'm guided to the scenario overview. My agent is now set as the ref. agent, i guess because no other agents exist.

Clicking in either Agent Overview or Agent Study will result in nothing happening. There are some exceptions thrown, for example if i click Agent Overview:

> Exception on /_dash-update-component [POST]
> Traceback (most recent call last):
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/venv_grid2viz/lib/python3.7/site-packages/grid2op/EpisodeData.py", line 155, in from_disk
>     with open(os.path.join(episode_path, EpisodeData.PARAMS)) as f:
> FileNotFoundError: [Errno 2] No such file or directory: '/home/jmenke/Documents/PythonProjects/Grid2Viz/grid2viz/data/agents/nodisc_powerlinegreedy/000/_parameters.json'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/venv_grid2viz/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/venv_grid2viz/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/venv_grid2viz/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/venv_grid2viz/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
>     raise value
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/venv_grid2viz/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/venv_grid2viz/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/venv_grid2viz/lib/python3.7/site-packages/dash/dash.py", line 1459, in dispatch
>     response.set_data(self.callback_map[output]["callback"](*args))
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/venv_grid2viz/lib/python3.7/site-packages/dash/dash.py", line 1339, in add_context
>     output_value = func(*args, **kwargs)  # %% callback invoked %%
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/grid2viz/index.py", line 135, in display_page
>     return macro.layout(timestamps, scenario, study_agent), "macro"
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/grid2viz/src/macro/macro_lyt.py", line 261, in layout
>     indicator_line(scenario, study_agent),
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/grid2viz/src/macro/macro_lyt.py", line 19, in indicator_line
>     episode = make_episode(study_agent, scenario)
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/grid2viz/src/manager.py", line 49, in make_episode
>     episode = compute_episode(episode_name, agent)
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/grid2viz/src/manager.py", line 89, in compute_episode
>     path, episode_name
>   File "/home/jmenke/Documents/PythonProjects/Grid2Viz/venv_grid2viz/lib/python3.7/site-packages/grid2op/EpisodeData.py", line 173, in from_disk
>     raise Grid2OpException(f"EpisodeData file not found \n {str(ex)}")
> grid2op.Exceptions.Grid2OpException: Grid2OpException "EpisodeData file not found 
>  [Errno 2] No such file or directory: '/home/jmenke/Documents/PythonProjects/Grid2Viz/grid2viz/data/agents/nodisc_powerlinegreedy/000/_parameters.json'"
> 127.0.0.1 - - [01/Apr/2020 09:22:53] "POST /_dash-update-component HTTP/1.1" 500 -

Is the nodisc_powerlinegreedy a static value in the code? My agent's logs are in another folder

**Comment by vinault** [comment]
Hi @jhmenke,

does the file /home/jmenke/Documents/PythonProjects/Grid2Viz/grid2viz/data/agents/nodisc_powerlinegreedy/000/_parameters.json exist ? 

We fixed a bug recently that tried to load agents on a scenario on which it did not run. If The above file does not exist, this is probably the same bug. You should not be able to reproduce it right now. Could you have a run at it please ?

Thanks
