### ISSUE TITLE
Data table in Scenario Overview not working when adding loads or generators

### ISSUE THREAD

**Issue by marota** [mjothy/grid2viz#72]
![image](https://user-images.githubusercontent.com/5496312/100996876-e5e0ab80-3559-11eb-8d4a-f80008131cc9.png)

Tested on Grid2viz Binder Demo, scenario dec_12_1.

We can see that the data-table looks empty when selecting a generator while we can display its time-serie above

**Comment by vinault** [comment]
In your example, the do_nothing agent did not survive the first day (8th of Dec) which led to a DatePicker with start_date==end_date==8th of Dec and end_date was previously filtered out of the table. I changed this behavior to filter in end_date.
